const caregiverSeeds = [
  {
		id: 'ca-nic-bRbEFAdRpPihA47EZ4kL',
		first_name: 'Nick',
		last_name: ' Nurse',
    email: 'nicknurse@basketball.com',
		password: '$2b$12$fNnGo60D/19iB6U0yKg8H.jzp.vlKR3oAQNUVJsX3uKz9qeihZSyC',
		phone_number: '905-123-4567',
		location: 'South Core, TO',
		birthdate: '1967-07-24',
		gender: 'MALE',
		years_experience: 10,
		description: 'I have had the privilege of providing care and assisting our elders for over 10 years. I have worked both for agencies and for private families and individuals with different needs and physical abilities. I am able to assist with dementia care, bathing, exercises and ROM, meal preparation and feeding, housekeeping, respite care, bed bound care, medicine reminders, transfers, lift experienced, transportation.',
		average_rating: '3.83',
		hourly_rate: 14,
		availability: 'LIVEOUT',
		avatar: 'https://www.catster.com/wp-content/uploads/2018/05/A-gray-cat-crying-looking-upset.jpg',
  },
  {
		id: 'ca-mik-hyJ1YCv5diQct6eB.LH5',
		first_name: 'Mike',
		last_name: 'Babcock',
    email: 'mikebabcock@hockey.com',
		password: '$2b$12$rglqSuxQbiGZJJy/DtKwbuDsEv55RzpcTw2iDmd9ccy8vIrukCCrK',
		phone_number: '905-456-7890',
		location: 'Corktown, TO',
		birthdate: '1963-04-29',
		gender: 'MALE',
		years_experience: 18,
		description: "I am a dependable , compassionate and loving caregiver. I have been working in the home care industry for 18 yrs . I pride myself on being able to quickly learn new skills and adapt to any situation. In the past I have clients who are diagnosed with Alzheimer, Dementia, Parkinson's , Mental , Cancer patient and Hospice. I assist them with their daily living activities , engaged in conversation , laundry , cooking meals . taken vital and maintained a clean household. I try to connect with my clients, spending time with them, going for walks and driving them to Dr's appointments , Shopping. etc I have my Washington State Caregiving Certificates, CPR license and Resume on hand",
		average_rating: '4.20',
		hourly_rate: 22,
		availability: 'LIVEIN',
		avatar: 'https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
  },
	{
		id: 'ca-mar-zrEODfqusvw4e1HLp8vU',
		first_name: 'Marie-Philip',
		last_name: 'Poulin',
    email: 'mariepoulin@hockey.com',
		password: '$2b$12$g6E5here.8d2AKSFA/8xPeDW4ZajdKDvVJ.QJklm9wZ6IE8U9OVom',
		phone_number: '905-321-9876',
		location: 'Kensington, TO',
		birthdate: '1991-03-28',
		gender: 'FEMALE',
		years_experience: 7,
		description: "I enjoy working with clients of all ages and socioeconomic backgrounds and have a demonstrated ability to develop great relationships with them and their families. Moreover, I am a trustworthy and responsible person who takes great pleasure in all kinds of care-giving tasks. Besides, I am dedicated to work hard and always accept challenges to produce winning outcomes. Over and above, I am an active team player who is able to work effectively with all involved. I have over 19 years hands on experience which includes a certification in Hospice care and Mental Health First Aid. As a passionate and reliable caregiver I LOVE my work. These rewarding experiences are never forgotten. I'd welcome a chance to meet with you to discuss how my education, experience and care-giving skills would be beneficial for you and your loved ones needs. I live in Morrisville, NC, and I understand the journey you're on.",
		average_rating: '3.91',
		hourly_rate: 15,
		availability: 'LIVEOUT',
		avatar: 'https://amp.businessinsider.com/images/55c906efdd0895b0558b45bc-1136-852.jpg',
	}
]

module.exports = caregiverSeeds